export const PARSE_TRACKS_QUEUE = 'PARSE_TRACKS_QUEUE';
export const PARSE_ARTISTS_QUEUE = 'PARSE_ARTISTS_QUEUE';
export const PARSE_ALBUMS_QUEUE = 'PARSE_ALBUMS_QUEUE';
export const SONGS_INFO_QUEUE = 'SONGS_INFO_QUEUE';
