export const PARSE_TRACKS_QUEUE = 'PARSE_TRACKS_QUEUE';
export const PARSE_ARTISTS_QUEUE = 'PARSE_ARTISTS_QUEUE';
export const PARSE_ALBUMS_QUEUE = 'PARSE_ALBUMS_QUEUE';
export const SONGS_INFO_QUEUE = 'SONGS_INFO_QUEUE';

export const SONGS_INFO_CHANNEL = 'SONGS_INFO_CHANNEL';
export const SONGS_INFO_EXTERNAL_DATA_CHANNEL =
  'SONGS_INFO_EXTERNAL_DATA_CHANNEL';
export const SONGS_INFO_PARSE_AND_CREATE = 'SONGS_INFO_PARSE_AND_CREATE';
export const SONGS_INFO_PROCESS_TRACK = 'SONGS_INFO_PROCESS_TRACK';
export const SONGS_INFO_PARSE_BY_URL = 'SONGS_INFO_PARSE_BY_URL';
