export const SENDER_SERVICE = 'SENDER_SERVICE';
export const BOT_SERVICE = 'BOT_SERVICE';
export const MESSAGES_SERVICE = 'MESSAGES_SERVICE';

export const ACTIONS = {
  NOW_PLAYING: 'NOW_PLAYING',
  SPOTIFY_SEARCH: 'SPOTIFY_SEARCH',
  DONATE: 'DONATE',
};
