export const DISTRIBUTED_SINGLE_FLIGHT_PUB = 'DISTRIBUTED_SINGLE_FLIGHT_PUB';
export const DISTRIBUTED_SINGLE_FLIGHT_SUB = 'DISTRIBUTED_SINGLE_FLIGHT_SUB';
export const DISTRIBUTED_SINGLE_FLIGHT = 'DISTRIBUTED_SINGLE_FLIGHT';
