export const staticPrefix = '/static';

export enum CLIENT_PROVIDES {
  TELEGRAM,
  TELEGRAM_2,
}

export type TELEGRAM_CLIENT_PROVIDERS =
  | CLIENT_PROVIDES.TELEGRAM
  | CLIENT_PROVIDES.TELEGRAM_2;

export enum CLIENT_UNIQUE_PROVIDES {
  TELEGRAM,
}

export enum MUSIC_SERVICE_PROVIDERS {
  SPOTIFY,
  SOUNDCLOUD,
}

export enum MUSIC_SERVICE_PROVIDER_NAMES {
  SPOTIFY = 'spotify',
  SOUNDCLOUD = 'soundcloud',
}

export const MUSIC_SERVICE_NAMES_BY_PROVIDERS: Record<
  MUSIC_SERVICE_PROVIDERS,
  MUSIC_SERVICE_PROVIDER_NAMES
> = {
  [MUSIC_SERVICE_PROVIDERS.SPOTIFY]: MUSIC_SERVICE_PROVIDER_NAMES.SPOTIFY,
  [MUSIC_SERVICE_PROVIDERS.SOUNDCLOUD]: MUSIC_SERVICE_PROVIDER_NAMES.SOUNDCLOUD,
} as const;
export const MUSIC_SERVICE_PROVIDERS_BY_NAME: Record<
  MUSIC_SERVICE_PROVIDER_NAMES,
  MUSIC_SERVICE_PROVIDERS
> = {
  [MUSIC_SERVICE_PROVIDER_NAMES.SPOTIFY]: MUSIC_SERVICE_PROVIDERS.SPOTIFY,
  [MUSIC_SERVICE_PROVIDER_NAMES.SOUNDCLOUD]: MUSIC_SERVICE_PROVIDERS.SOUNDCLOUD,
} as const;

export const INTERNAL_MUSIC_SERVICE_PROVIDER = 'INTERNAL' as const;
export type INTERNAL_MUSIC_SERVICE_PROVIDER =
  typeof INTERNAL_MUSIC_SERVICE_PROVIDER;

export const INTERNAL_MUSIC_SERVICE_NAME = 'itrn' as const;
export type INTERNAL_MUSIC_SERVICE_NAME = typeof INTERNAL_MUSIC_SERVICE_NAME;
