export const staticPrefix = '/static';

export enum CLIENT_PROVIDES {
  TELEGRAM,
  TELEGRAM_2,
}

export type TELEGRAM_CLIENT_PROVIDERS =
  | CLIENT_PROVIDES.TELEGRAM
  | CLIENT_PROVIDES.TELEGRAM_2;

export enum CLIENT_UNIQUE_PROVIDES {
  TELEGRAM,
}

export enum MUSIC_SERVICE_PROVIDERS {
  SPOTIFY,
  // SOUNDCLOUD,
}
